In [1]:
import numpy as np

In [ ]:
def calH(alpha):
    alpha[0,0]-=np.linalg.norm(alpha)
    omega=alpha/np.linalg.norm(alpha)
    oo=omega@omega.T
    H=np.eye(oo.shape[0])-2*oo
    return H

B=np.array([[0,3,1],[0,4,-2],[2,1,1]])
print(B)
alpha=B[:,0].reshape(-1,1)
print(alpha)
H=calH(alpha)
print(H)

[[ 0  3  1]
 [ 0  4 -2]
 [ 2  1  1]]
[[0]
 [0]
 [2]]
[[2.22044605e-16 0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00 2.22044605e-16]]


In [ ]:
def calH(alpha):
    alpha[0,0]-=np.linalg.norm(alpha)
    omega=alpha/np.linalg.norm(alpha)
    oo=omega@omega.T
    H=np.eye(oo.shape[0])-2*oo
    return H

def calQ(calH,A):
    n=A.shape[0]
    subA=A.copy()
    for ii in range(n-1):
        alpha=subA[:,0].reshape(-1,1)
        h=calH(alpha)
        H=np.eye(n)
        H[ii:,ii:]=h
        A=H@A
        subA=A[ii+1:,ii+1:].copy()
    return A[:,:]
B=np.array([[0,3,1],[0,4,-2],[2,1,1]])
A=np.array([[10,7,8,7],
            [7,5,6,5],
            [8,6,10,9],
            [7,5,9,10]])
R=calQ(calH,A)
print(R)

[[ 1.61818182e+01  1.16060606e+01  1.63030303e+01  1.51818182e+01]
 [ 3.52449221e-01  5.47135457e-01  3.26435112e+00  3.28784773e+00]
 [ 1.72468275e-02  7.79833442e-17  2.13429490e+00  3.63476889e+00]
 [-1.55699789e-01  3.44532047e-17 -1.04519274e-16 -7.00649050e-01]]
